name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Build Docker Image
      run: docker build -t ${{ secrets.alinaaftab }}/python-app:latest .

    - name: Login to DockerHub
      run: docker login -u ${{ secrets.DOCKERHUBUSERNAME }} -p ${{ secrets.DOCKERHUBTOKEN }}

    - name: Push Docker Image
      run: docker push ${{ secrets.alinaaftab }}/python-app:latest
